# Generated by Django 6.0.1 on 2026-01-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('team', models.CharField(max_length=30, null=True)),
                ('role', models.CharField(choices=[('DUELISTA', 'Duelista'), ('SENTINELA', 'Sentinela'), ('CONTROLADOR', 'Controlador'), ('INICIADOR', 'Iniciador'), ('FLEX', 'Flex')])),
                ('foto', models.CharField(max_length=30)),
            ],
        ),
    ]
